# Generated by Django 6.0 on 2025-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_reminded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
